### ISSUE TITLE
Zaws and Amps?

### ISSUE THREAD

**Issue by Mulchman** [South-Paw/warframe-item-list#1]
Zaw Strikes and Amp Prisms count towards mastery, once they're ranked up and then gilded, and then ranked up again. I did a dump of your data and didn't see either mentioned, thus this issue being created.

Zaw Strike names
* Balla
* Ooltha
* Kronsh
* Dehtat
* Mewan
* Cyath

Amp Prism names
*  Mote Amp (I don't actually know what the Prism for this Amp is called; this is the already crafted Amp that's given to you for free)
* Raplak
* Shwaak
* Granmu

**Comment by South-Paw** [comment]
Thanks for the list.

I wrote this package pretty shortly after Plains of Eidolon had released so the wiki didn't contain much info on Amps and Zaws but it seems now that there is [sections](http://warframe.wikia.com/wiki/Mastery_Rank) for them and it's clear there are no mastery rank requirements or anything.

I'll go about adding them to the package this evening 👍

**Comment by Mulchman** [comment]
Awesome, thanks!
