### ISSUE TITLE
22.8.0 outstanding items

### ISSUE THREAD

**Issue by Mulchman** [South-Paw/warframe-item-list#14]
22.8.0 is out: https://forums.warframe.com/topic/897989-plains-of-eidolon-update-2280/

I made https://github.com/South-Paw/warframe-item-list/pull/13 for the Corinth but there are ~~3~~ 2 other weapons in 22.8.0:

* ~~Gunsen~~
  * ~~MR: 10~~
  * ~~Acquisition: Tenno Lab~~
  * ~~Category: Unsure which category in `constants.js` to put this under and/or if it needs a new one for its type.~~ 

* Stubba
  * MR: 5
  * Acquisition: Ghoul Purge bounties from Konzu in Cetus (needs new `constants.js` entry?)
  * Category: ~~Grineer Submachine Gun (so maybe it's a primary like the Baza then? Unknown at this time.)~~ I got the blueprint. It's a secondary... so `SINGLE_PISTOL`? Or make a new category?

* Quartarkk
  * MR: 9
  * Acquisition: Ghoul Purge bounties from Konzu in Cetus (needs new `constants.js` entry?)
  * Category: Rifle

**Comment by Mulchman** [comment]
I got the new stance, Slicing Feathres, and it says it's for "WARFANS" so that should be the new category for the Gunsen.

**Comment by Mulchman** [comment]
Updated the PR to include the Warfans melee category and then added the Gunsen. Stubba and Quatark remain.

**Comment by Mulchman** [comment]
Stubba is a secondary. Should a new category, `SUBMACHINE_GUN`, be added to `secondaryCategory` in `constanats.js`? Or just file this one under `SINGLE_PISTOL`?

**Comment by South-Paw** [comment]
@Mulchman There's another weapon which was a 'sub-machine gun' but the Warframe wiki lists it as a Pistol - so I marked it as such too, so let's go with that again.

**Comment by South-Paw** [comment]
It also looks like there are actually 4 new weapons (as per: http://warframe.wikia.com/wiki/Update_22#Update_22.8.0)

- [x] [Corinth](http://warframe.wikia.com/wiki/Corinth)
- [x] [Gunsen](http://warframe.wikia.com/wiki/Gunsen)
- [ ] [Quartakk](http://warframe.wikia.com/wiki/Quartakk)
- [ ] [Stubba](http://warframe.wikia.com/wiki/Stubba)

I'll add the missing two now.

**Comment by Mulchman** [comment]
Yeah, there are 4: I submitted a PR with 2 (Corinth and Gunsen) then
created an issue for the other 2 (Quartakk and Stubba) because I didn't
know how you wanted to categorize them since they're from an
event/Cetus/Konzu.

On Dec 21, 2017 22:24, "Alex Gabites" <notifications@github.com> wrote:

It also looks like there are actually 4 new weapons (as per:
http://warframe.wikia.com/wiki/Update_22#Update_22.8.0)

   - Corinth <http://warframe.wikia.com/wiki/Corinth>
   - Gunsen <http://warframe.wikia.com/wiki/Gunsen>
   - Quartakk <http://warframe.wikia.com/wiki/Quartakk>
   - Stubba <http://warframe.wikia.com/wiki/Stubba>

I'll add the missing two now.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/South-Paw/warframe-item-list/issues/14#issuecomment-353531229>,
or mute the thread

**Comment by South-Paw** [comment]
Ahh right, makes sense. I'll look at them now - cheers 👍

**Comment by South-Paw** [comment]
@Mulchman does #15 add/solve everything?

**Comment by Mulchman** [comment]
Yes!

**Comment by South-Paw** [comment]
Merged #15 and published to npm
