### ISSUE TITLE
23.4.0 - new prism (Rahn Prism)

### ISSUE THREAD

**Issue by Mulchman** [South-Paw/warframe-item-list#35]
There's a new prism with 23.4.0: `Rahn Prism`.

I've been swamped and can't make a proper PR, but wanted to throw it out there.

**Comment by South-Paw** [comment]
I'll look at adding it tonight, cheers for raising an issue - helps me be aware there's an update 👍 

Also looking at how to handle this better in the future (ie; back on generating the data instead of manually adding)
