### ISSUE TITLE
23.6.0 - new item(s?)

### ISSUE THREAD

**Issue by Mulchman** [South-Paw/warframe-item-list#39]
Spoilers... and there may be others (I'm only on the second part of the 'quest').

* Zylok - secondary - MR6

EDIT: it appears that Zylok is the only new Mastery item with this event.

**Comment by South-Paw** [comment]
Regarding this issue, #38 #37 and #35 - I'm working on a mostly automated update script for the project.

Changes would still need to be committed into the repo and there would be some manual mapping required for things that can't be parsed from the apis but overall we should be better off with it than without it.

I know I said I didn't want to but there are just too many changes to keep up with so might as well use what's there while it is there 😃

**Comment by South-Paw** [comment]
I've just pushed some WIP changes towards this and am still actively working on it tonight, check it out here if you're interested: https://github.com/South-Paw/warframe-item-list/tree/api-generated

**Comment by andersbrandt** [comment]
Love the new concept of fetching generated content - the final hurdle are removed to move towards fully auto-generated content, and not relying on manual updates :)
Code looks good as well.

However i'm not as positive to removing the acquisition-variable - I believe it's an important piece of information for users of any app based on this data. To keep acquisition as a manual data-enrichment using mapping might be a viable solution? Fresh data for currently vaulted items can be fetched from https://warframe.wikia.com/wiki/Prime_Vault

**Comment by andersbrandt** [comment]
You can see how acquisition are used in my app here:
https://andersbrandt.se/warframe/helper/ 

Examples where acquisition comes handy:
- Search for "boss, filter Unranked = All Warframes left for simple farming
- Search for "baro", filter Unranked = All items still available from Barry
- Search for "quest", filter Unranked = All items available from quests
